//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel;
using System.ComponentModel.DataAnnotations;

namespace TiendaMVC.Models
{
    using System;
    using System.Collections.Generic;

    public partial class Producto
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Producto()
        {
            this.ProductoAlmacen = new HashSet<ProductoAlmacen>();
            this.Etiqueta = new HashSet<Etiqueta>();
        }

        public int IdProducto { get; set; }
        [DisplayName("PON EL ID ENTRE 1 y 2")]
        [Range(1,2,ErrorMessage = "Introduce un valor entre 1 y 2")]
        public int IdCategoria { get; set; }
        [Required(ErrorMessage = "El Nombre del producto es OBLIGATORIO")]
        [DisplayName("Product: ")] /*DisplayName es el nombre de la etiqueta*/
        public string NombreProducto { get; set; }

        [DisplayName("Fabricante")]
        public string Fabricante { get; set; }
        public Nullable<double> PC { get; set; }
        [DisplayName("PVP")]
        [DataType(DataType.Currency)] 
        public double PVP { get; set; }
        public int IdEtiqueta { get; set; }
      
        public virtual Categoria Categoria { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProductoAlmacen> ProductoAlmacen { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Etiqueta> Etiqueta { get; set; }
    }
}
